title: Official Website of Jay Lafray
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5182599
  brandStrength: 0.125
  lightness: 1
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#e2012b'
    - '#742e64'
    - '#8c86a8'
  rhythmicContrast: 0.679377
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Jay Lafray
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4272517445497215
layout_spectrum: 0.13004
