name: Jay Lafray
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4272517445497215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#e2012b'
    - '#742e64'
    - '#8c86a8'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
